server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      data-locations: "classpath*:/data.sql"
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
jwt:
  expiration_time: 86400
  secret: MjAyNDA2XzMwM19qYXZhX3NlY3JldF9jaG9pamluc2lsCg==